/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hitcrt_rm0422.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hitcrt_rm0422.pb-c.h"
void   message_to__cpu__init
                     (MessageToCPU         *message)
{
  static const MessageToCPU init_value = MESSAGE_TO__CPU__INIT;
  *message = init_value;
}
size_t message_to__cpu__get_packed_size
                     (const MessageToCPU *message)
{
  assert(message->base.descriptor == &message_to__cpu__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_to__cpu__pack
                     (const MessageToCPU *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_to__cpu__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_to__cpu__pack_to_buffer
                     (const MessageToCPU *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_to__cpu__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageToCPU *
       message_to__cpu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageToCPU *)
     protobuf_c_message_unpack (&message_to__cpu__descriptor,
                                allocator, len, data);
}
void   message_to__cpu__free_unpacked
                     (MessageToCPU *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_to__cpu__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_to__mcu__init
                     (MessageToMCU         *message)
{
  static const MessageToMCU init_value = MESSAGE_TO__MCU__INIT;
  *message = init_value;
}
size_t message_to__mcu__get_packed_size
                     (const MessageToMCU *message)
{
  assert(message->base.descriptor == &message_to__mcu__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_to__mcu__pack
                     (const MessageToMCU *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_to__mcu__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_to__mcu__pack_to_buffer
                     (const MessageToMCU *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_to__mcu__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageToMCU *
       message_to__mcu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageToMCU *)
     protobuf_c_message_unpack (&message_to__mcu__descriptor,
                                allocator, len, data);
}
void   message_to__mcu__free_unpacked
                     (MessageToMCU *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_to__mcu__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message_to__cpu__field_descriptors[6] =
{
  {
    "current_pitch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MessageToCPU, current_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function_select",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToCPU, function_select),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserved_float1",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MessageToCPU, reserved_float1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserved_float2",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MessageToCPU, reserved_float2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserved_int2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToCPU, reserved_int2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserved_int3",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToCPU, reserved_int3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_to__cpu__field_indices_by_name[] = {
  0,   /* field[0] = current_pitch */
  1,   /* field[1] = function_select */
  2,   /* field[2] = reserved_float1 */
  3,   /* field[3] = reserved_float2 */
  4,   /* field[4] = reserved_int2 */
  5,   /* field[5] = reserved_int3 */
};
static const ProtobufCIntRange message_to__cpu__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor message_to__cpu__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message_to_CPU",
  "MessageToCPU",
  "MessageToCPU",
  "",
  sizeof(MessageToCPU),
  6,
  message_to__cpu__field_descriptors,
  message_to__cpu__field_indices_by_name,
  1,  message_to__cpu__number_ranges,
  (ProtobufCMessageInit) message_to__cpu__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message_to__mcu__field_descriptors[6] =
{
  {
    "target_flag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToMCU, target_flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aim_pitch",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MessageToMCU, aim_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aim_yaw",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MessageToMCU, aim_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(MessageToMCU, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buff_state",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToMCU, buff_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heart_beat",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToMCU, heart_beat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_to__mcu__field_indices_by_name[] = {
  1,   /* field[1] = aim_pitch */
  2,   /* field[2] = aim_yaw */
  4,   /* field[4] = buff_state */
  3,   /* field[3] = distance */
  5,   /* field[5] = heart_beat */
  0,   /* field[0] = target_flag */
};
static const ProtobufCIntRange message_to__mcu__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor message_to__mcu__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message_to_MCU",
  "MessageToMCU",
  "MessageToMCU",
  "",
  sizeof(MessageToMCU),
  6,
  message_to__mcu__field_descriptors,
  message_to__mcu__field_indices_by_name,
  1,  message_to__mcu__number_ranges,
  (ProtobufCMessageInit) message_to__mcu__init,
  NULL,NULL,NULL    /* reserved[123] */
};
